name: solana_wallet
description: A solana mobile wallet

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  solana: ^0.13.0

dev_dependencies:
  mobx: ^2.0.0
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  redux_persist: ^0.9.0
  redux_persist_flutter: ^0.9.0
  dart_json_mapper: ^2.1.12
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
